apiVersion: 1

datasources:
  - name: MongoDB
    type: grafana-mongodb-datasource
    access: proxy
    url: mongodb://admin:admin123@mongodb:27017
    database: nids_db
    isDefault: true
    editable: true
