apiVersion: 1

datasources:
  # Infinity datasource for querying JSON APIs (free alternative to MongoDB datasource)
  - name: NIDS-API
    type: yesoreyeram-infinity-datasource
    uid: infinity-datasource
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      # Will connect to the dashboard API for alert data
      allowedHosts:
        - http://host.docker.internal:5000
